In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"C:\Users\Gultac\Desktop\Desktop\Insurance Customer Churn & Risk Analysis\train.csv")
df.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381109 entries, 0 to 381108
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    381109 non-null  int64
 1   Gender                381109 non-null  object
 2   Age                   381109 non-null  int64
 3   Driving_License       381109 non-null  int64
 4   Region_Code           381109 non-null  float64
 5   Previously_Insured    381109 non-null  int64
 6   Vehicle_Age           381109 non-null  object
 7   Vehicle_Damage        381109 non-null  object
 8   Annual_Premium        381109 non-null  float64
 9   Policy_Sales_Channel  381109 non-null  float64
 10  Vintage               381109 non-null  int64
 11  Response              381109 non-null  int64
dtypes: float64(3), int64(6), object(3)
memory usage: 34.9+ MB

In [5]:
df.isnull().sum()

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

In [6]:
df.describe()

,id,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage,Response
count,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000
mean,190555.000000,38.822584,0.997869,26.388807,0.458210,30564.389581,112.034295,154.347397,0.122563
std,110016.836208,15.511611,0.046110,13.229888,0.498251,17213.155057,54.203995,83.671304,0.327936
min,1.000000,20.000000,0.000000,0.000000,0.000000,2630.000000,1.000000,10.000000,0.000000
25%,95278.000000,25.000000,1.000000,15.000000,0.000000,24405.000000,29.000000,82.000000,0.000000
50%,190555.000000,36.000000,1.000000,28.000000,0.000000,31669.000000,133.000000,154.000000,0.000000
75%,285832.000000,49.000000,1.000000,35.000000,1.000000,39400.000000,152.000000,227.000000,0.000000
max,381109.000000,85.000000,1.000000,52.000000,1.000000,540165.000000,163.000000,299.000000,1.000000

In [7]:
df = df.drop("id", axis=1)

In [13]:
print(df["Gender"].value_counts(), "\n",
df["Vehicle_Age"].value_counts(), "\n",
df["Vehicle_Damage"].value_counts())

Gender
Male      206089
Female    175020
Name: count, dtype: int64
 Vehicle_Age
1-2 Year     200316
< 1 Year     164786
> 2 Years     16007
Name: count, dtype: int64
 Vehicle_Damage
Yes    192413
No     188696
Name: count, dtype: int64

In [14]:
df.groupby("Gender")["Response"].mean()

Gender
Female    0.103902
Male      0.138411
Name: Response, dtype: float64

In [ ]:
#Kisi müştərilər sığorta məhsullarına daha meyilli görünür

In [15]:
df.groupby("Vehicle_Age")["Response"].mean()

Vehicle_Age
1-2 Year     0.173755
< 1 Year     0.043705
> 2 Years    0.293746
Name: Response, dtype: float64

In [ ]:
#Daha köhnə avtomobili olan müştərilər daha yüksək risk və sığorta ehtiyacı göstərir

In [16]:
df.groupby("Vehicle_Damage")["Response"].mean()

Vehicle_Damage
No     0.005204
Yes    0.237655
Name: Response, dtype: float64

In [17]:
#Vehicle damage olan müştərilərdə response rate çox yüksəkdir, bu da onların sığorta məhsullarına daha meyilli olduğunu göstərir.
#Maşını zədələnmiş adam daha çox sığorta istəyir

In [18]:
df["Gender"] = df["Gender"].map({"Male":1, "Female":0})

In [19]:
df["Gender"].value_counts()

Gender
1    206089
0    175020
Name: count, dtype: int64

In [20]:
df["Vehicle_Damage"] = df["Vehicle_Damage"].map({"Yes":1, "No":0})

In [21]:
df["Vehicle_Damage"].value_counts()

Vehicle_Damage
1    192413
0    188696
Name: count, dtype: int64

In [22]:
df["Vehicle_Age"] = df["Vehicle_Age"].map({
    "< 1 Year":0,
    "1-2 Year":1,
    "> 2 Years":2
})

In [23]:
df["Vehicle_Age"].value_counts()

Vehicle_Age
1    200316
0    164786
2     16007
Name: count, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [25]:
X = df.drop("Response", axis=1)
y = df["Response"]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

C:\Users\Gultac\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [30]:
model = LogisticRegression(max_iter=2000)

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.93     66699
           1       0.50      0.00      0.00      9523

    accuracy                           0.88     76222
   macro avg       0.69      0.50      0.47     76222
weighted avg       0.83      0.88      0.82     76222

In [ ]:
#Model initially class imbalance səbəbindən minority class-ı düzgün proqnozlaşdıra bilmədi.datada:0  çox 1  az

In [31]:
model = LogisticRegression(max_iter=2000, class_weight="balanced")

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.59      0.74     66699
           1       0.26      0.98      0.40      9523

    accuracy                           0.64     76222
   macro avg       0.62      0.78      0.57     76222
weighted avg       0.90      0.64      0.70     76222

In [32]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.89      0.97      0.93     66699
           1       0.38      0.12      0.18      9523

    accuracy                           0.87     76222
   macro avg       0.63      0.55      0.55     76222
weighted avg       0.82      0.87      0.83     76222

In [ ]:
#Random Forest daha yüksək accuracy versə də, churn edən müştəriləri tapmaqda zəif idi. Buna görə recall göstəricisi yüksək olan 
#Logistic Regression modelini seçdim.

In [33]:
y_prob = model.predict_proba(X_test_scaled)[:,1]

In [34]:
y_prob

array([0.00361203, 0.72350512, 0.74901548, ..., 0.0032849 , 0.00366072,
       0.0041354 ])

In [35]:
risk_df = X_test.copy()
risk_df["Risk_Score"] = y_prob

In [36]:
def risk_level(x):
    if x < 0.3:
        return "Low"
    elif x < 0.7:
        return "Medium"
    else:
        return "High"

risk_df["Risk_Level"] = risk_df["Risk_Score"].apply(risk_level)

In [37]:
risk_df.head()

,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Risk_Score,Risk_Level
200222,0,21,1,3.0,1,0,0,20408.0,160.0,72,0.003612,Low
49766,1,55,1,15.0,0,1,1,37498.0,26.0,102,0.723505,High
172201,0,41,1,3.0,0,1,1,2630.0,26.0,90,0.749015,High
160713,0,26,1,11.0,0,0,0,2630.0,151.0,268,0.155141,Low
53272,1,51,1,40.0,0,1,1,34006.0,124.0,265,0.686783,Medium

In [38]:
risk_df.groupby("Risk_Level")["Risk_Score"].mean()

Risk_Level
High      0.752922
Low       0.029295
Medium    0.625573
Name: Risk_Score, dtype: float64